apiVersion: v1
kind: Service
metadata:
  labels:
    app: argocd-api
  name: argocd-api
  namespace: app
spec:
  ports:
    - name: 8080-8080
      nodePort: 30080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: argocd-api
  type: NodePort